/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 20/01/2021 03:26:15
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     216000000
#define MX_HCLKFreq_Value                       216000000
#define MX_FCLKCortexFreq_Value                 216000000
#define MX_CortexFreq_Value                     216000000
#define MX_AHBFreq_Value                        216000000
#define MX_APB1Freq_Value                       54000000
#define MX_APB2Freq_Value                       108000000
#define MX_APB1TimFreq_Value                    108000000
#define MX_APB2TimFreq_Value                    216000000
#define MX_EthernetFreq_Value                   216000000
#define MX_CECFreq_Value                        32786
#define MX_I2C1Freq_Value                       54000000
#define MX_I2C2Freq_Value                       54000000
#define MX_I2C3Freq_Value                       54000000
#define MX_I2C4Freq_Value                       54000000
#define MX_I2SFreq_Value                        192000000
#define MX_SAI1Freq_Value                       192000000
#define MX_SAI2Freq_Value                       192000000
#define MX_SDMMCFreq_Value                      216000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     108000000
#define MX_USART2Freq_Value                     54000000
#define MX_USART3Freq_Value                     54000000
#define MX_UART4Freq_Value                      54000000
#define MX_UART5Freq_Value                      54000000
#define MX_UART8Freq_Value                      54000000
#define MX_UART7Freq_Value                      54000000
#define MX_USART6Freq_Value                     108000000
#define MX_USBFreq_Value                        216000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     54000000
#define MX_SPDIFRXFreq_Value                    192000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    216000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/*-------------------------------- SPDIFRX    --------------------------------*/

#define MX_SPDIFRX                              1

/* GPIO Configuration */

/* Pin PG12 */
#define MX_SPDIFRX_IN1_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_SPDIFRX_IN1_Pin                      PG12
#define MX_SPDIFRX_IN1_GPIOx                    GPIOG
#define MX_SPDIFRX_IN1_GPIO_PuPd                GPIO_NOPULL
#define MX_SPDIFRX_IN1_GPIO_Pin                 GPIO_PIN_12
#define MX_SPDIFRX_IN1_GPIO_AF                  GPIO_AF7_SPDIFRX
#define MX_SPDIFRX_IN1_GPIO_Mode                GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPDIF_RX_DT */
#define MX_SPDIF_RX_DT_DMA_DMA_Handle
#define MX_SPDIF_RX_DT_DMA_Instance             DMA1_Stream1
#define MX_SPDIF_RX_DT_DMA_FIFOMode             DMA_FIFOMODE_DISABLE
#define MX_SPDIF_RX_DT_DMA_Priority             DMA_PRIORITY_LOW
#define MX_SPDIF_RX_DT_DMA_Channel              DMA_CHANNEL_0
#define MX_SPDIF_RX_DT_DMA_PeriphDataAlignment  DMA_PDATAALIGN_WORD
#define MX_SPDIF_RX_DT_DMA_MemDataAlignment     DMA_MDATAALIGN_WORD
#define MX_SPDIF_RX_DT_DMA_Mode                 DMA_CIRCULAR
#define MX_SPDIF_RX_DT_DMA_Direction            DMA_PERIPH_TO_MEMORY
#define MX_SPDIF_RX_DT_DMA_PeriphInc            DMA_PINC_DISABLE
#define MX_SPDIF_RX_DT_DMA_MemInc               DMA_MINC_ENABLE
#define MX_SPDIF_RX_DT_DMA_IpInstance

/* NVIC Configuration */

/* NVIC SPDIF_RX_IRQn */
#define MX_SPDIF_RX_IRQn_interruptPremptionPriority 0
#define MX_SPDIF_RX_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_SPDIF_RX_IRQn_Subriority             0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD8 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_TX_Pin                        PD8
#define MX_USART3_TX_GPIOx                      GPIOD
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_8
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3

/* Pin PD9 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART3_RX_Pin                        PD9
#define MX_USART3_RX_GPIOx                      GPIOD
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

